swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Read the entire set of people, sorted by last name
      description: Read the entire set of people, sorted by last name
      responses:
        200:
          description: Successfully read people set operation
          schema:
            type: array
            items:
              properties:
                office:
                  type: string
                  description: Id of the person
                fio:
                  type: string
                  description: Fio
                birthday:
                  type: string
                  description: birthday
                office:
                  type: string
                  description: doljnost
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the person

    post:
      operationId: people.create
      tags:
        - People
      summary: Create a person
      description: Create a new person
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fio:
                type: string
                description: fio
              birthday:
                type: string
                description: birthday
              office:
                type: string
                description: office
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              office:
                type: string
                description: Id of the person
              fio:
                type: string
                description: fio
              birthday:
                type: string
                description: birthday
              office:
                type: string
                description: office
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

  /people/{office}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: filter by office
      description: filter by office
      parameters:
        - name: office
          in: path
          description: Id of the person to get
          type: string
          required: True
      responses:
        200:
          description: Successfully read person filter by office
          schema:
            type: object
            properties:
              office:
                type: string
                description: Id of the person
              fio:
                type: string
                description: fio
              birthday:
                type: string
                description: birthday
              office:
                type: string
                description: office
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

    put:
      operationId: people.update
      tags:
        - People
      summary: Update a person
      description: Update a person
      parameters:
        - name: office
          in: path
          description: Id the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fio:
                type: string
                description: fio
              birthday:
                type: string
                description: birthday
              office:
                type: string
                description: office
      responses:
        200:
          description: Successfully updated person
          schema:
            properties:
              office:
                type: string
                description: Id of the person in the database
              fio:
                type: string
                description: fio
              birthday:
                type: string
                description: birthday
              office:
                type: string
                description: office
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

    delete:
      operationId: people.delete
      tags:
        - People
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: office
          in: path
          type: integer
          description: Id of the person to delete
          required: true
      responses:
        200:
          description: Successfully deleted a person


